# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 


from snakemake.utils import min_version

min_version("7.30.0")


container: "docker://continuumio/miniconda3"

rule hello_world:
  conda:
      "base"
  log: "logs/hello_world.log"
  shell:
    'echo "Hello World!"'