# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 


from snakemake.utils import min_version

min_version("6.3.0")



configfile: "config/config.yaml"

# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
container: "docker://continuumio/miniconda3"




include: "rules/common.smk"


# rule hello_world:
#   conda:
#       "base"
#   log: "logs/hello_world.log"
#   shell:
#     'echo "Hello World!"'